//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPROJECTMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesVenta
    {
        public int iIdDetalle { get; set; }
        public int iIdVenta { get; set; }
        public int iIdProducto { get; set; }
        public decimal dCantidad { get; set; }
        public decimal dPrecio { get; set; }
        public decimal dPorcentajeIVA { get; set; }
        public decimal dMontoIVA { get; set; }
        public decimal dPorcentajeDescuento { get; set; }
        public decimal dMontoDescuento { get; set; }
        public bool lActivo { get; set; }
        public System.DateTime dtAlta { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
    }
}
