//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPROJECTMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int iIdProducto { get; set; }
        public int iIdCategoria { get; set; }
        public Nullable<int> iIdMarca { get; set; }
        public string cNombre { get; set; }
        public string cDescripcion { get; set; }
        public string cCodigo { get; set; }
        public decimal dPrecio { get; set; }
        public decimal dCantidadExistente { get; set; }
        public decimal dMinimo { get; set; }
        public bool lPublicado { get; set; }
        public bool lActivo { get; set; }
        public System.DateTime dtAlta { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
    }
}
