--DROP DATABASE STOCKSHOP
--CREATE DATABASE STOCKSHOP

CREATE TABLE Categorias(
	iIdCategoria INT PRIMARY KEY IDENTITY NOT NULL,
	cNombre VARCHAR(MAX) NOT NULL,
	cDescripcion VARCHAR(MAX),
	lActivo BIT NOT NULL DEFAULT 1,
	dtAlta DATETIME NOT NULL,
	dtModificacion DATETIME
);

CREATE TABLE Marcas(
	iIdMarca INT PRIMARY KEY IDENTITY NOT NULL,
	cNombre VARCHAR (MAX) NOT NULL,
	lActivo BIT NOT NULL DEFAULT 1,
	dtAlta DATETIME NOT NULL,
	dtModificacion DATETIME
);

CREATE TABLE Productos(
	iIdProducto INT PRIMARY KEY IDENTITY NOT NULL,
	iIdCategoria INT NOT NULL,
	iIdMarca INT,
	cNombre VARCHAR(MAX) NOT NULL,
	cDescripcion VARCHAR(MAX),
	cCodigo VARCHAR(MAX) NOT NULL,
	dPrecio DECIMAL(18,2) NOT NULL,
	dCantidadExistente DECIMAL(18,2) NOT NULL,
	dMinimo DECIMAL(18,2) NOT NULL DEFAULT 5,
	lPublicado BIT NOT NULL DEFAULT 0,
	lActivo BIT NOT NULL DEFAULT 1,
	dtAlta DATETIME NOT NULL,
	dtModificacion DATETIME
);

CREATE TABLE Ventas(
	iIdVenta INT PRIMARY KEY IDENTITY NOT NULL,
	iIdUsuario INT NOT NULL,
	cNombreCliente VARCHAR(MAX) NOT NULL,
	dMonto DECIMAL(18,2) NOT NULL,
	lActivo BIT NOT NULL DEFAULT 1,
	dtAlta DATETIME NOT NULL,
	dtModificacion DATETIME
);

CREATE TABLE DetallesVenta(
	iIdDetalle INT PRIMARY KEY IDENTITY NOT NULL,
	iIdVenta INT NOT NULL,
	iIdProducto INT NOT NULL,
	dCantidad DECIMAL(18,2) NOT NULL,
	dPrecio DECIMAL(18,2) NOT NULL,
	dPorcentajeIVA DECIMAL(18,2) NOT NULL,
	dMontoIVA DECIMAL(18,2) NOT NULL,
	dPorcentajeDescuento DECIMAL(18,2) NOT NULL,
	dMontoDescuento DECIMAL(18,2) NOT NULL,
	lActivo BIT NOT NULL DEFAULT 1,
	dtAlta DATETIME NOT NULL,
	dtModificacion DATETIME
);